### ISSUE TITLE
Pre-aggregations with S3 export bucket

### ISSUE THREAD

**Issue by artusmok91** [cube-js/cube.js#3372]
**Problem**

Hi, 

I am trying to use pre-aggregations with S3 export bucket, but I am seeing quite a few issues. I am sourcing the data from Snowflake. 

I am getting the following errors:
- “Create table failed: Internal: Invalid gzip header”
- “Create table failed: Internal: invalid digit found in string”
- “Create table failed: Internal: invalid float literal”

What may be causing them and how can I better debug them? Is it possibly caused by the S3 setup (if so, how should it be configured to work with Cube.js)?
It appears to me that the numeric ID1 and ID2 dimensions are causing the problem (their values range from 1 to about 40,000). When I tried using another column (that is a string) for pre-aggregations, I didn't get the error. Are there any restrictions on what dimension types can be used for pre-aggregations?

**Related Cube.js schema**
```javascript
cube(`Foo`, {
  sql: `SELECT * FROM VW_FOO`,
  measures: {
    SUM: {
      type: `sum`,
      sql: `BAR`
    }
  },

  dimensions: {
    DATE: {
      sql: `DATE`,
      type: `time`,
      primaryKey: true,
      shown: true
    },
    ID1: {
      sql: `ID1`,
      type: `number`,
      primaryKey: true,
      shown: true
    },
    ID2: {
      sql: `ID2`,
      type: `number`,
      primaryKey: true,
      shown: true
    }
  },
  
  preAggregations: {
    foo_preagg: {
      measures: [
        foo.SUM
      ],
      dimensions: [
        foo.ID2,
        foo.ID1
      ],
      timeDimension: foo.DATE,
      granularity: `day`,
      partitionGranularity: `month`,
      buildRangeStart: {
        sql: `SELECT CURRENT_DATE - interval '365 day'`
      },
      buildRangeEnd: {
        sql: `SELECT CURRENT_DATE`
      },
      refreshKey: {
        sql: `select FLOOR(DATE_PART('EPOCH_SECOND', TO_TIMESTAMP_LTZ (current_timestamp())) / 3600)`
      }
    }
  },

  refreshKey: {
    sql: `select FLOOR(DATE_PART('EPOCH_SECOND', TO_TIMESTAMP_LTZ (current_timestamp())) / 86400)` //refresh cache everyday

  },

  dataSource: `default`
});
```

**Related Cube.js generated SQL**

```
Error during create table: CREATE TABLE pre_aggregations.foo_preagg20210701_blah (`foo___i_d_1` decimal, `foo___i_d_2` decimal, `foo___d_a_t_e_day` timestamp, `foo___s_u_m` decimal)  LOCATION ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?: User: Create table failed: Internal: invalid digit found in string
    at QueryQueue.parseResult (..\cubejs\node_modules\@cubejs-backend\server-core\node_modules\@cubejs-backend\query-orchestrator\src\orchestrator\QueryQueue.js:136:13)
    at QueryQueue.executeInQueue (..\cubejs\node_modules\@cubejs-backend\server-core\node_modules\@cubejs-backend\query-orchestrator\src\orchestrator\QueryQueue.js:125:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at PreAggregationLoader.loadPreAggregationWithKeys (..\cubejs\node_modules\@cubejs-backend\server-core\node_modules\@cubejs-backend\query-orchestrator\src\orchestrator\PreAggregations.ts:585:7)
    at async Promise.all (index 0)
    at PreAggregationPartitionRangeLoader.loadPreAggregations (..\cubejs\node_modules\@cubejs-backend\server-core\node_modules\@cubejs-backend\query-orchestrator\src\orchestrator\PreAggregations.ts:1150:27)
    at QueryOrchestrator.fetchQuery (..\cubejs\node_modules\@cubejs-backend\server-core\node_modules\@cubejs-backend\query-orchestrator\src\orchestrator\QueryOrchestrator.ts:97:59)
    at OrchestratorApi.executeQuery (..\cubejs\node_modules\@cubejs-backend\server-core\src\core\OrchestratorApi.ts:57:20)
    at ..\cubejs\node_modules\@cubejs-backend\api-gateway\src\gateway.ts:827:26
    at async Promise.all (index 0)
    at ApiGateway.load (..\cubejs\node_modules\@cubejs-backend\api-gateway\src\gateway.ts:812:23)
    at ..\cubejs\node_modules\@cubejs-backend\api-gateway\src\gateway.ts:282:7
Orchestrator error: 749e6bc9-5656-4226-8646-074e1bcb7023-span-18 (1505ms)
```

```
2021-09-02 14:59:35,877 ERROR [cubestore::cluster] <pid:36224> Running job error (158.2215ms): IdRow { id: 9268, row: Job { row_reference: Table(Tables, 410), job_type: TableImportCSV("https://foo.s3.eu-west-2.amazonaws.com/bar/foo.csv.gz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=foo&X-Amz-Date=20210902T135923Z&X-Amz-Expires=3600&X-Amz-Signature=bar&X-Amz-SignedHeaders=host&x-id=GetObject"), last_heart_beat: 2021-09-02T13:59:35.877696700Z, status: Error("Internal: invalid digit found in string") } }
```

Thank you,
Artur

**Comment by artusmok91** [comment]
I have managed to isolate and fix the underlying issue - there were null values in numeric columns. 

I have now set up pre-aggregations, however they are a bit "moody" - they work for short date ranges, but when I pre-aggregated a year, my local instance usually shows the following error:
`Internal: Execution error: Internal: File not found: ...\foo\.cubestore\data\38.parquet`
Deleting .cubestore folder fixes it, but it means I need to re-run pre-aggregations. 

I've also deployed to Openshift, but the error is: 
`Internal: Arrow error: External error: Arrow error: Invalid argument error: Merge operation on unsorted data: Cursor [array: 0, row: 2, value: [1628035200000000]], Cursor [array: 0, row: 3, value: [1617235200000000]]`

**Comment by paveltiunov** [comment]
Hey @artusmok91 ! Are you using `CUBESTORE_REMOTE_DIR` setting?

**Comment by paveltiunov** [comment]
@artusmok91 You might want to upgrade to the latest version and see if problem still persists.

**Comment by paveltiunov** [comment]
Please see https://github.com/cube-js/cube.js/issues/3510#issuecomment-980786498 for related conversation.
